let currentSlide = 0;
const lastSlide = 30;

//canvas setup
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

//1420 wide x 450 high at least
if ((window.innerWidth - 10) < 1420){
    canvas.width=1420;
} else {
    canvas.width=window.innerWidth - 10;
}
if ((window.innerHeight * 0.55) < 450){
    canvas.height = 450;
} else {
    canvas.height = (window.innerHeight) * 0.55;
}

setSlide();
let text_Y_val = 0;
let offsetVal = 0;

//key press functionality
document.addEventListener("keydown", function(event) {
    event.preventDefault();
    switch (event.key) {
        case "ArrowLeft":
            switchSlide('L');
            break;
        case "ArrowRight":
            switchSlide('R');
            break;
        default:
            //nothing yet
            break;
    }
});

//functions
function switchSlide(x) {
    switch (x) {
        case 'L':
            //go to previous slide
            if (currentSlide > 0){
                currentSlide -= 1;
                setSlide();
                setSlideSource();
            }
            break;
        case 'R':
            //go to next slide
            if (currentSlide < lastSlide){
                currentSlide += 1;
                setSlide();
                setSlideSource();
            }
            break;
        default:
            //do nothing
            break;
    }
    return true;
}

//clear canvas and apply current slide to canvas. called by switchSlide()
function setSlide() {
    //clear canvas
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    //hide video, buttons
    hideNextButton();
    hideVideo();
    showVideo();
    hideButtons();
    //create text shadow
    //gradient & shadow from https://www.html5canvastutorials.com/tutorials/html5-canvas-gradient-text-tutorial/
    ctx.shadowColor = "rgba(83,149,170,0.69)";
    ctx.shadowOffsetX = 10;
    ctx.shadowOffsetY = 10
    ctx.shadowBlur = 10;
    //add slide number to bottom right corner
    if (currentSlide > 0){
        ctx.font="20px Georgia";
        ctx.fillStyle = "rgba(94, 94, 94, 0.69)";
        ctx.fillText(String(currentSlide) + "/" + String(lastSlide), canvas.width - 55, canvas.height - 20);
    }
    //create text gradient
    let gradient = ctx.createLinearGradient(0, 0, canvas.width * 0.7, canvas.height * 0.3);
    gradient.addColorStop(0, "rgb(0,185,253)");
    gradient.addColorStop(1, "rgb(15,229,181)");
    ctx.fillStyle = gradient;
    //apply current slide to canvas
    switch(currentSlide) {
        case 0:
            ctx.font= String(canvas.width * 0.05) + "px Georgia";
            ctx.fillText("AI-Generated Music", canvas.width * 0.1, canvas.height * 0.2);
            ctx.font="20px Georgia";
            ctx.fillText("Raven O'Rourke | PMUS 1001 | Summer 2020", canvas.width * 0.5, canvas.height * 0.8);
            ctx.shadowColor = "transparent";
            ctx.fillText("← Use the left and right arrows on your keyboard to navigate slides →", canvas.width * 0.3, canvas.height * 0.5);
            ctx.fillText("↓ Sources will be linked under slides ↓", canvas.width * 0.1, canvas.height - 20);
            break;
        case 1:
            text_Y_val = fillSlide("AI-Generated Music: What is it?",
                "Computers and music can interact in a variety of ways. For instance, Spotify uses a machine learning algorithm to create daily",
                "personalized playlists for its users, and Shazam creates an acoustic fingerprint to identify songs from auditory input.");
            break;
        case 2:
            text_Y_val = fillSlide("AI-Generated Music: What is it?",
                "Computers and music can interact in a variety of ways. For instance, Spotify uses a machine learning algorithm to create daily",
                "personalized playlists for its users, and Shazam creates an acoustic fingerprint to identify songs from auditory input.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "This presentation will focus on music generated by artificial intelligence using neural networks. It's basically a computer\'s ",
                "best attempt at creating music, usually based off of \"real music\" input that the computer tries to imitate.");
            break;
        case 3:
            //neural network diagram
            drawImageOnSlide("neuralnetdiagram", 100, 100, 0.4);
            text_Y_val = fillSlide("How is it created?",
                "Artificial neural networks are used to train computers to generate new music.");
            break;
        case 4:
            //neural network diagram
            drawImageOnSlide("neuralnetdiagram", 100, 100, 0.4);
            text_Y_val = fillSlide("How is it created?",
                "Artificial neural networks are used to train computers to generate new music.");
            //text to right of image
            text_Y_val += 30;
            //bulletpoint
            ctx.fillText("→", 525, text_Y_val);
            ctx.fillText("A defining feature of artificial intelligence (versus other types of computing)", 550, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("is that it possesses a ", 550, text_Y_val);
            offsetVal = 550 + ctx.measureText("is that it possesses a ").width;
            ctx.font = "bold 20px Georgia";
            ctx.fillText("feedback loop ", offsetVal, text_Y_val);
            offsetVal += ctx.measureText("feedback loop ").width;
            ctx.font = "20px Georgia";
            ctx.fillText("which helps the computer learn and get better.", offsetVal, text_Y_val);
            break;
        case 5:
            //neural network diagram
            drawImageOnSlide("neuralnetdiagram", 100, 100, 0.4);
            text_Y_val = fillSlide("How is it created?",
                "Artificial neural networks are used to train computers to generate new music.");
            //text to right of image
            text_Y_val += 30;
            //bulletpoint
            ctx.fillText("→", 525, text_Y_val);
            ctx.fillText("Everything gets represented by a number so that the computer can", 550, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("put it through an algorithm. ", 550, text_Y_val);
            //new bulletpoint
            text_Y_val += 30;
            ctx.fillText("→", 525, text_Y_val);
            ctx.fillText("The computer can be given numbers representing:", 550, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("•", 550, text_Y_val);
            ctx.fillText("Pitch (Example: C = 1, C♯ = 2, D = 3, etc.)", 575, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("•", 550, text_Y_val);
            ctx.fillText("Octave (Example: 1, 2, 3, or 4 representing successively higher octaves)", 575, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("•", 550, text_Y_val);
            ctx.fillText("Note duration", 575, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("•", 550, text_Y_val);
            ctx.fillText("A note's relative position in the song", 575, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("(Example: Current measure number divided by total number of measures)", 575, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("•", 550, text_Y_val);
            ctx.fillText("And much more. Every aspect of music can be represented numerically", 575, text_Y_val);
            text_Y_val += 30;
            ctx.fillText("and used to develop the neural network.", 575, text_Y_val);
            break;
        case 6:
            showButtons();
            fillSlide("History");
            ctx.fillText("Take a guess: when was the first computer-generated composition created?", (canvas.width * 0.5) - 300, (canvas.height * 0.5) - 30 );
            break;
        case 7:
            text_Y_val = fillSlide("History",
                "Believe it or not, the first computer composition was created in 1957! \"Illiac Suite for String Quartet\" was created as a collaboration between",
                "composer Lejaren Hiller and mathematician Leonard Isaacson. ");
            newBulletPoint(text_Y_val);
            //todo add info about markov chain
            text_Y_val = fillSlide(" ", " ", " ",
                "This piece was generated using a Markov Chain, a method that uses probability to determine which notes are likely to follow each other.");
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", " ", " ",
                "It was then recorded by human musicians.", " ",
                "Below is the first piece from the suite.");
            break;
        case 8:
            //todo Ray Kurzweil (with his collection of Tom Swift, Jr. books, which he read as a child) Circa 2003. Credit: Photo by Michael Lutch. Courtesy of Kurzweil Technologies, Inc.
            text_Y_val = fillSlide("History",
                "Another notable computer composition was featured on the television",
                "show \"I\'ve Got a Secret\" in 1965.",);
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "Raymond Kurzweil is famous today as an author, inventor, and outspoken ",
                "futurist and is currently employed as a director of engineering at Google.");
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", " ", " ", " ",
                "He is around 17 in the video below, where he performs his piece and the ",
                "panelists must guess that it is computer-generated.");
            drawImageOnSlide("kurzweil", 800, 50, 0.3);
            break;
        case 9:
            text_Y_val = fillSlide("Modern Methods: Computer Composition",
                "Both of the previous examples were composed by computers and then recorded by humans.");
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", "This is still a popular method today, and a search for \"AI Music\" on YouTube or Google will mostly return compositions of this type.");
            break;
        case 10:
            text_Y_val = fillSlide("Modern Methods: Computer Composition",
                "Both of the previous examples were composed by computers and then recorded by humans.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", "This is still a popular method today, and a search for \"AI Music\" on YouTube or Google will mostly return compositions of this type.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "Aiva Technologies, a Luxembourgian company founded in 2016, has created a program that makes this method easily accessible.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ",
                "AIVA (Artificial Intelligence Virtual Artist), the company's AI composer, uses machine learning methodology, including deep learning ",
                "(using neural networks) and reinforcement learning (using probability) to create compositions.");
            break;
        case 11:
            text_Y_val = fillSlide("Modern Methods: Computer Composition",
                "Both of the previous examples were composed by computers and then recorded by humans.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", "This is still a popular method today, and a search for \"AI Music\" on YouTube or Google will mostly return compositions of this type.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "Aiva Technologies, a Luxembourgian company founded in 2016, has created a program that makes this method easily accessible.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ",
                "AIVA (Artificial Intelligence Virtual Artist), the company's AI composer, uses machine learning methodology, including deep learning ",
                "(using neural networks) and reinforcement learning (using probability) to create compositions.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ", " ", " ",
                "One of AIVA's creators, Pierre Barreau, believes that personalized music has potential as a new frontier. ",
                "He aims to use AIVA to create pieces, in the style of great composers like Beethoven and Mozart, which are tailored to individuals' tastes.");
            break;
        case 12:
            text_Y_val = fillSlide("Modern Methods: Computer Composition",
                "Below, the input I used to create a song using AIVA.");
            drawImageOnSlide("aivainput", 20, text_Y_val + 10, 0.35);
            ctx.fillText("The program took less than a minute to create a unique rock song.", 45, 310);
            ctx.fillText("However, without paying for the rights, I am unable to download the MP3 to share.", 45, 340);


            drawImageOnSlide("midifile", 800, 20, 0.3);
            ctx.fillText("Right, a visual", 650, text_Y_val + 30);
            ctx.fillText("representation", 650, text_Y_val + 60);
            ctx.fillText("of the MIDI", 650, text_Y_val + 90);
            ctx.fillText("file of the song", 650, text_Y_val + 120);
            ctx.fillText("created by AIVA.", 648, text_Y_val + 150);
            ctx.fillText("→", 760, text_Y_val + 180);
            break;
        case 13:
            text_Y_val = fillSlide("Modern Methods: Lyric Generation", "AI can also write lyrics!");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", "Many lyric generators exist on the internet. Here's an example of");
            text_Y_val = fillSlide(" ", " ", " "," some lyrics generated by the site \"TheseLyricsDoNotExist.com\"");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ",
                "This site uses a neural network to generate lyrics fitting a user\'s");
            text_Y_val += 30;
            text_Y_val = fillSlide(" ", " ", " ", " ", " ", "selected topic and style.(*cite)");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ", " ", " ", "Below is the input used to generate these lyrics:");
            drawImageOnSlide("lyrics1", 110, 260, 0.4);
            drawImageOnSlide("lyrics2", 700, 20, 0.4);
            drawImageOnSlide("lyrics3", 1050, 20, 0.4);
            break;
        case 14:
            text_Y_val = fillSlide("Modern Methods: Audio Synthesis", "" +
                "The electronic synthesis of instrument sounds has been around for decades now. ",
                "When combined with AI, the results can be really amazing.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "OpenAI is a San Francisco artificial intelligence research center, founded in 2015 ",
                "with the mission to \"develop \'digital intelligence\'that will benefit humanity.\"");
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", " ", " ", " ",
                "In April 2020, OpenAI unveiled \"Jukebox\", a neural network that generates music (vocals included).");
            break;
        case 15:
            text_Y_val = fillSlide("Modern Methods: Audio Synthesis", "In the below example, OpenAI's Jukebox attempted to extend an existing song.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "OpenAI says of this method, ");
            offsetVal = 95 + ctx.measureText("OpenAI says of this method,  ").width;
            ctx.font = "bold 20px Georgia";
            ctx.fillText("\"We provide 12 seconds of audio to condition on and Jukebox completes the rest in a specified style.\"", offsetVal, text_Y_val);
            offsetVal += ctx.measureText("\"We provide 12 seconds of audio to condition on and Jukebox completes the rest in a specified style.\"").width;
            ctx.font = "20px Georgia";
            ctx.fillText("(cite)", offsetVal, text_Y_val);
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", " ",
                "The AI has access to the full lyrics, as well as the genre and artist, as it attempts to continue the song.",
                " ", " ", "The AI synthesis begins at 0:12.");
            break;
        case 16:
            fillSlide("Is it good?", "What do people think?");
            drawImageOnSlide("good2", 100, 100, 0.35);
            drawImageOnSlide("good1", 790, 100, 0.39);
            ctx.fillText("→ Reviews are mixed, with some implementations being better than others.", 75, 300);
            break;
        case 17:
            text_Y_val = fillSlide("Is it good?", "In 1997, UCSC professor David Cope created software that created new music in the style of Bach.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "The piece was performed for an audience alongside a genuine Bach composition, as well as a human-created piece imitating Bach's style.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "The audience believed that the computer-created composition was genuine Bach.");
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", " ", " ",
                "The event generated controversy as some people found it disrespectful to people like Bach who spent their lives composing music,",
                "and it raised questions about what should be considered to be \'art\'.");
            fillSlide(" ", " ", " ", " ", " ", " ", " ",
                "The composition, performed by humans, is below.");
            break;
        case 18:
            text_Y_val = fillSlide("Is it good?",
                "A 2019 study commissioned by AI company Amper Music found that panelists were unable to discern between human- and computer-composed music, ",
                "and also showed no strong preference for one or the other.");
            break;
        case 19:
            text_Y_val = fillSlide("Is it good?",
                "A 2019 study commissioned by AI company Amper Music found that panelists were unable to discern between human- and computer-composed music, ",
                "and also showed no strong preference for one or the other.");
            newBulletPoint(text_Y_val);
            fillSlide(" ", " ", " ",
                "For a 2020 survey by ticket vendor TickPick, participants were shown AI-generated lyrics for rock, rap, country, and pop songs.",
                "In many cases, a majority of participants attributed the lyrics to popular human artists. Some of the lyrics were so good that 65% of participants",
                "rated them as the most creative lyrics, and 39.6% rated them the most emotional, compared to 3 human-written lyrics that they",
                "were shown alongside.");
            break;
        case 20:
            text_Y_val = fillSlide("Is it good?",
                "Some AI implementations have gotten very good at synthesizing voices.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "Below, an OpenAI imitation of Frank Sinatra. The lyrics are funny and absurd; OpenAI says they were \"co-written\"",
                "by AI and humans. However, the vocal synthesis is very realistic.");
            break;
        case 21:
            text_Y_val = fillSlide("So good, it might be illegal",
                "The ability to convincingly imitate popular artists raises legal questions.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "Below, a \"deepfake\" (deep learning + fake) of Jay-Z rapping the lyrics to Billy Joel's \"We Didn't Start the Fire\".");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "This audio was created using Google's open source program \"Tacotron 2\".");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ",
                "The AI does an excellent job of imitating not just Jay-Z's voice, but also his cadence.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ", " ",
                "Jay-Z's record label filed a copyright claim against the video on the grounds that \"this content unlawfully uses an AI to",
                "impersonate our client’s voice\". However, YouTube determined that the copyright claim was incomplete, and the video remains",
                "up for now. ");
            break;
        case 22:
            text_Y_val = fillSlide("So good, it might be illegal",
                "Does Jay-Z have grounds for a copyright claim?");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "\"Amanda Levendowski, a professor at Georgetown Law and founding director of its Intellectual Property and Information Policy Clinic, ",
                "says that while, at first look, the Jay-Z situation may look like a copyright issue regarding the data used to create the voice, it’s actually ",
                "closer in spirit to prior legal cases of human impersonators.\"(*cite Medium article)");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ", " ",
                "A 1988 case ruled that vocal imitation in commercial materials is not protected if it does nothing but exploit the person's identity, and",
                "a 1991 case established legal precedent for rights to a person's likeness. ");
            break;
        case 23:
            text_Y_val = fillSlide("So good, it might be illegal",
                "The anonymous creator of the Jay-Z audio has stated, \"I don’t really understand why mimicking a celebrity’s voice using",
                "an AI model should be treated differently than someone naturally doing an (extremely accurate) impression of that celebrity’s voice.\"");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
            "Technologist and anti-censorship activist Andy Baio says that the case is in uncharted waters, but that the clear labeling",
                "of the audio as synthesized and the lack of intent to deceive may protect the creator.");
            break;
        case 24:
            text_Y_val = fillSlide("Further Questions", "Who owns the copyright to works created by AI?");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "The question of whether a computer can legally be considered an author was raised in 1965 by the US Copyright Office.");
            break;
        case 25:
            text_Y_val = fillSlide("Further Questions", "Who owns the copyright to works created by AI?");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "The question of whether a computer can legally be considered an author was raised in 1965 by the US Copyright Office.");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ",
                "The Compendium of US Copyright Office Practices and the US Court of Appeals for the Ninth Circuit have determined that",
                "animals, plants, supernatural beings, and \"works produced by a machine or mere mechanical process that operates randomly ",
                "or automatically\" cannot legally be considered authors. Does this apply to AI, which is capable of adapting and improving?");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ", " ", " ",
                "Aiva Technologies seems confident that works created with their AIVA program belong to the company, although",
                "they offer the option for users to purchase full rights to their creations.");
            break;
        case 26:
            fillSlide("Further Questions", "How will it affect musicians and composers?");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ",
                "Former presidential candidate Andrew Yang warns that millions of American workers will be replaced by machines.",
                "Will AI replace artists?");
            newBulletPoint(text_Y_val);
            text_Y_val = fillSlide(" ", " ", " ", " ",
                "AIVA's FAQ section answers this question:");
            drawImageOnSlide("aivareplace", 100, 200, 0.6);
            break;
        case 27:
            fillSlide("Further Questions", "In 2018, musician Taryn Southern released an album ");
            break;
        case 27:
            fillSlide("Future", "could it create a popular song, trend or longevity? ");
            break;
            //todo impact on songwriters and musicians
        //todo future: trend or longetivity? could it creat a popular song?
        //todo add all sources
        default:
            ctx.fillText("Slide " + String(currentSlide), 20, 300);
            break;
    }
    return true;
}

//fill generic slide with title and text
function fillSlide(title, l1="", l2="", l3="", l4="", l5="", l6="", l7="") {
    //title
    ctx.font= "36px Georgia";
    ctx.fillText(title, 30, 50);

    //text
    ctx.font= "20px Georgia";
    ctx.shadowColor = "transparent";

    let text_Y_val = 90;
    if (l1 !==""){
        ctx.fillText("→ " + l1, 75, text_Y_val);
    }
    if (l2 !== ""){
        text_Y_val += 30;
        ctx.fillText(l2, 100, text_Y_val);
    } else return text_Y_val;
    if (l3 !== ""){
        text_Y_val += 30;
        ctx.fillText(l3, 100, text_Y_val);
    } else return text_Y_val;
    if (l4 !== ""){
        text_Y_val += 30;
        ctx.fillText(l4, 100, text_Y_val);
    } else return text_Y_val;
    if (l5 !== ""){
        text_Y_val += 30;
        ctx.fillText(l5, 100, text_Y_val);
    } else return text_Y_val;
    if (l6 !== ""){
        text_Y_val += 30;
        ctx.fillText(l6, 100, text_Y_val);
    } else return text_Y_val;
    if (l7 !== ""){
        text_Y_val += 30;
        ctx.fillText(l7, 100, text_Y_val);
    } else return text_Y_val;
}

function newBulletPoint(text_Y_val){
    text_Y_val += 30;
    ctx.fillText("→ ", 75, text_Y_val);
}

//show youtube video with same number as current slide
function showVideo() {
    let video_source = "";
    //get video source
    switch(currentSlide){
        case 7:
            //hiller illiac suite
            video_source = "https://www.youtube.com/embed/n0njBFLQSk8";
            break;
        case 8:
            //kurzweil
            video_source = "https://www.youtube.com/embed/X4Neivqp2K4?start=16";
            break;
        case 15:
            //uptown funk extended
            video_source = "https://www.youtube.com/embed/KCaya74_NHw";
            break;
        case 17:
            //undiscovered bach
            video_source = "https://www.youtube.com/embed/PczDLl92vlc";
            break;
        case 20:
            //hot tub time
            video_source = "https://www.youtube.com/embed/OQy1BciDxEc";
            break;
        case 21:
            //jay-z
            video_source = "https://www.youtube.com/embed/iyemXtkB-xk";
            break;
        default:
            video_source = "none";
            break;
    }
    //change source of video element
    document.getElementById("video").src = video_source;
    //show video if there is one
    if (video_source === "none"){
        return;
    } else {
        showNextButton();
        document.getElementById("video").style.visibility="visible";
    }
}

//show next button (for slides with youtube videos)
function showNextButton(){
    document.getElementById("nextbutton").style.display = "inline";
}
//hide next button
function hideNextButton(){
    document.getElementById("nextbutton").style.display = "none";
}

//hide all youtube videos
function hideVideo() {
    document.getElementById("video").style.visibility="hidden";
}

//show buttons below canvas
function showButtons() {
    document.getElementById("buttons").style.display = "inline";
}
//hide buttons below canvas
function hideButtons(){
    document.getElementById("buttons").style.display = "none";
}

//put image on canvas slide. takes address of image, x/y coords for canvas, and percent to multiply size
function drawImageOnSlide(image_id, x_val, y_val, size_pct) {
    let img = document.getElementById(image_id);
    let img_width = img.width * size_pct;
    let img_height = img.height * size_pct;
    ctx.drawImage(img, x_val, y_val, img_width, img_height);
}

//identify source names and links
let sn1 = "(1) Company - Shazam. Shazam, www.shazam.com/company. Accessed 22 July 2020.";
let sl1 = "https://www.shazam.com/company";
let sn2 = "(2) \"Spotify + The Machine: Using Machine Learning to Create Value and Competitive Advantage.\" MBA Student Perspectives, Harvard Business School, 13 Nov. 2018"
let sl2 = "https://digital.hbs.edu/platform-rctom/submission/spotify-the-machine-using-machine-learning-to-create-value-and-competitive-advantage/"
let sn3 = "(3) \"1950s: The Beginnings of Artificial Intelligence (AI) Research.\" World-Information.org, World-Information Institute.";
let sl3 = "https://world-information.org/wio/infostructure/100437611663/100438659360";
let sn4 = "(4) \"I Created an AI That Wrote Music\". YouTube, uploaded by Qxir, 1 March 2019.";
let sl4 = "https://www.youtube.com/watch?v=8lQh2QAgeIQ&list=PLk9Xpzkm63TUI2PwNui0SaE_Yp_Dmwsok";
let sn5 = "(5) Hiller, Lejaren et al. \"Computer Music.\" Encyclopædia Britannica, Encyclopædia Britannica, Inc., 21 Feb. 2018.";
let sl5 = "https://www.britannica.com/art/electronic-music/Computer-music";
let sn6 = "";
let sl6 = "";

//sources to add
//these lyrics do not exist
//undiscovered bach https://www.youtube.com/embed/PczDLl92vlc

//change text for slide source under canvas
function setSlideSource(){
    switch(currentSlide){
        case 2:
        case 3:
            document.getElementById("sourcelink1").firstChild.nodeValue = sn1;
            document.getElementById("sourcelink1").setAttribute("href", sl1);
            document.getElementById("sourcelink2").firstChild.nodeValue = sn2;
            document.getElementById("sourcelink2").setAttribute("href", sl2);
            break;
        case 4:
        case 5:
        case 6:
            document.getElementById("sourcelink1").firstChild.nodeValue = sn3;
            document.getElementById("sourcelink1").setAttribute("href", sl3);
            document.getElementById("sourcelink2").firstChild.nodeValue = sn4;
            document.getElementById("sourcelink2").setAttribute("href", sl4);
            break;
        case 8:
            document.getElementById("sourcelink1").firstChild.nodeValue = sn5;
            document.getElementById("sourcelink1").setAttribute("href", sl5);
            break;
        default:
            document.getElementById("sourcelink1").firstChild.nodeValue = "";
            document.getElementById("sourcelink2").firstChild.nodeValue = "";
            document.getElementById("sourcelink3").firstChild.nodeValue = "";
            break;
    }
}

//behavior for button clicks: go to next slide, display correct if right answer
function clickButton(val){
    switchSlide('R');
    switch(val){
        case 1957:
            ctx.fillStyle = "black";
            ctx.fillRect(0,0,200,70);
            ctx.shadowColor = "rgba(83,149,170,0.69)";
            ctx.shadowOffsetX = 10;
            ctx.shadowOffsetY = 10
            ctx.shadowBlur = 10;
            let gradient = ctx.createLinearGradient(0, 0, canvas.width * 0.7, canvas.height * 0.3);
            gradient.addColorStop(0, "rgb(0,185,253)");
            gradient.addColorStop(1, "rgb(15,229,181)");
            ctx.fillStyle = gradient;
            ctx.font = "50px Georgia"
            ctx.fillText("Correct!", 0, 50);
            break;
        case 1968:
            break;
        case 1991:
            break;
        case 2002:
            break;
        default:
            break;
    }
}